namespace HashExperiment;

public class QuickAndDirtyHash
{
    // random string of bytes generated by System.Security.Cryptography.RandomNumberGenerator.GetBytes(16)
    private static readonly byte[] _key = [91, 64, 130, 201, 187, 50, 33, 90, 248, 238, 23, 162, 202, 150, 75, 184];

    public byte[] Hash(Span<byte> input)
    {
        byte[] result = new byte[_key.Length];
        _key.CopyTo(result, 0);

        for (int i = 0; i < input.Length; i++)
            result[i % result.Length] ^= input[i];

        return result;
    }
}
